CREATE OR REPLACE TRIGGER ZMIANA_LICZBY_MIEJSC
BEFORE UPDATE
ON WYCIECZKI
FOR EACH ROW
BEGIN
    IF :NEW.LICZBA_MIEJSC <> :OLD.LICZBA_MIEJSC THEN
        SELECT :OLD.LICZBA_WOLNYCH_MIEJSC + 
            (:NEW.LICZBA_MIEJSC - :OLD.LICZBA_MIEJSC)
        INTO :NEW.LICZBA_WOLNYCH_MIEJSC FROM DUAL;
    END IF;
END;
