CREATE TABLE REZERWACJE_LOG
(
    ID_LOG INT GENERATED ALWAYS AS IDENTITY NOT NULL,
    ID_REZERWACJI INT,
    DATA DATE,
    STATUS CHAR(1),
    CONSTRAINT REZERWACJE_LOG_PK PRIMARY KEY (ID_LOG) ENABLE
);

ALTER TABLE REZERWACJE_LOG
ADD CONSTRAINT REZERWACJE_LOG_FK 
FOREIGN KEY (ID_REZERWACJI) REFERENCES REZERWACJE(NR_REZERWACJI) ENABLE;

ALTER TABLE REZERWACJE_LOG
ADD CONSTRAINT REZERWACJE_LOG_CHK CHECK (STATUS IN ('N', 'P', 'Z', 'A')) ENABLE;
